from django.urls import path
from . import views

# Create your urls here.
urlpatterns = [
    path('', views.home, name='home'),
    path('blogs/', views.blog_list, name='blogs'),
    path('blog/<int:id>/', views.blog_detail, name='blog'),
    path('blog/create/', views.blog_create, name='create_blog'),
    path('blog/update/<int:id>/', views.blog_update, name='update_blog'),
    path('blog/delete/<int:id>/', views.blog_delete, name='delete_blog'),
    path('blog/comment/<int:id>/', views.comment_create, name='comment'),
    path('blog/comment/delete/<int:id>/', views.comment_delete, name='delete_comment'),
    path('blog/comment/update/<int:id>/', views.comment_update, name='update_comment'),
    path('categories/', views.category_list, name='categories'),
    path('category/create/', views.category_create, name='create_category'),
    path('category/<int:id>/', views.category_detail, name='category'),
    path('category/update/<int:id>/', views.category_update, name='update_category'),
    path('category/delete/<int:id>/', views.category_delete, name='delete_category'),
    path('tags/', views.tag_list, name='tags'),
    path('tag/create/', views.tag_create, name='create_tag'),
    path('tag/<int:id>/', views.tag_detail, name='tag'),
    path('tag/update/<int:id>/', views.tag_update, name='update_tag'),
    path('tag/delete/<int:id>/', views.tag_delete, name='delete_tag'),
    path('profile/', views.profile, name='profile'),
    path('profile/update/', views.update_profile, name='update_profile'),
    path('profile/delete/', views.delete_profile, name='delete_profile'),
    path('search/', views.search, name='search'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('contact/send/', views.send_contact, name='send_contact'),
    path('contact/delete/<int:id>/', views.delete_contact, name='delete_contact'),
    path('contact/reply/<int:id>/', views.reply_contact, name='reply_contact'),
    path('contact/reply/delete/<int:id>/', views.delete_reply, name='delete_reply'),
    path('contact/reply/update/<int:id>/', views.update_reply, name='update_reply'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('user_list/', views.user_list, name='user_list'),

]
